import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";

const sdkDir = new URL("../../mugon-sdk-js/", import.meta.url);

const { version } = JSON.parse(readFileSync(new URL("package.json", sdkDir), "utf8"));
writeFileSync(
  new URL("../internal/model/sdkversion.go", import.meta.url),
  `// Code generated by scripts/gen-sdk.mjs; DO NOT EDIT.\n\npackage model\n\nconst DefaultJsSdkVersion = "${version}"\n`,
);

const iife = new URL("dist/mugon.iife.js", sdkDir);
if (!existsSync(iife)) {
  throw new Error("build the SDK first: npm run build in libraries/mugon-sdk-js");
}
for (const template of ["minimal"]) {
  copyFileSync(
    iife,
    new URL(
      `../internal/templates/project/${template}/{{.DistributionDir}}/mugon.iife.js`,
      import.meta.url,
    ),
  );
}
