id = "test"
version = "0.1.0"
js-sdk-version = "0.1.0"
watch-paths = ["src", "index.html", "package-lock.json", "tsconfig.json"]

[[command]]
name = "install"
command = "npm install"

[[command]]
name = "build"
command = "npm run build"